# Generated by Django 4.2.15 on 2024-08-23 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodyPart', models.TextField()),
                ('weightType', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='ExerciseData',
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='exercises',
            field=models.ManyToManyField(to='myapp.exercise'),
        ),
    ]
