# Generated by Django 4.2.15 on 2024-08-23 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_exercise_delete_exercisedata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='name',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
