# Generated by Django 4.2.15 on 2024-08-23 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_workoutset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutsession',
            name='exercises',
        ),
        migrations.RemoveField(
            model_name='workoutset',
            name='exercise',
        ),
        migrations.CreateModel(
            name='WorkoutSessionExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_exercises', to='myapp.exercise')),
                ('workout_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_exercises', to='myapp.workoutsession')),
            ],
        ),
        migrations.AddField(
            model_name='workoutset',
            name='session_exercise',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='myapp.workoutsessionexercise'),
            preserve_default=False,
        ),
    ]
