# Generated by Django 4.2.15 on 2024-08-23 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_workoutsession_exercises_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='bodyPart',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='weightType',
        ),
    ]
